package services

import (
	"bytes"
	"fmt"

	"github.com/jung-kurt/gofpdf"
	"go-service/models"
)

type PDFGenerator struct{}

func NewPDFGenerator() *PDFGenerator {
	return &PDFGenerator{}
}

func (g *PDFGenerator) GenerateStudentReport(s *models.Student) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// header
	pdf.SetFont("Arial", "B", 20)
	pdf.CellFormat(190, 15, "Student Report", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(190, 10, s.Name, "", 1, "C", false, 0, "")
	pdf.Ln(5)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(10)

	// personal info
	g.section(pdf, "Personal Information")
	g.field(pdf, "Student ID", fmt.Sprintf("%d", s.ID))
	g.field(pdf, "Email", s.Email)
	g.field(pdf, "Phone", strVal(s.Phone))
	g.field(pdf, "Gender", strVal(s.Gender))
	g.field(pdf, "Date of Birth", strVal(s.DOB))
	pdf.Ln(5)

	// academic info
	g.section(pdf, "Academic Information")
	g.field(pdf, "Class", strVal(s.Class))
	g.field(pdf, "Section", strVal(s.Section))
	g.field(pdf, "Roll Number", intVal(s.Roll))
	g.field(pdf, "Admission Date", strVal(s.AdmissionDate))
	g.field(pdf, "Class Teacher", strVal(s.ReporterName))
	pdf.Ln(5)

	// guardian info
	g.section(pdf, "Guardian Information")
	g.field(pdf, "Father's Name", strVal(s.FatherName))
	g.field(pdf, "Father's Phone", strVal(s.FatherPhone))
	g.field(pdf, "Mother's Name", strVal(s.MotherName))
	g.field(pdf, "Mother's Phone", strVal(s.MotherPhone))
	g.field(pdf, "Guardian's Name", strVal(s.GuardianName))
	g.field(pdf, "Guardian's Phone", strVal(s.GuardianPhone))
	g.field(pdf, "Relation", strVal(s.RelationOfGuardian))
	pdf.Ln(5)

	// address
	g.section(pdf, "Address Information")
	g.field(pdf, "Current Address", strVal(s.CurrentAddress))
	g.field(pdf, "Permanent Address", strVal(s.PermanentAddress))
	pdf.Ln(5)

	// system access
	g.section(pdf, "System Status")
	status := "Inactive"
	if s.SystemAccess {
		status = "Active"
	}
	g.field(pdf, "System Access", status)

	// footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(190, 10, "Generated by School Management System", "", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (g *PDFGenerator) section(pdf *gofpdf.Fpdf, title string) {
	pdf.SetFont("Arial", "B", 12)
	pdf.SetFillColor(230, 230, 230)
	pdf.CellFormat(190, 8, title, "", 1, "L", true, 0, "")
	pdf.Ln(2)
}

func (g *PDFGenerator) field(pdf *gofpdf.Fpdf, label, value string) {
	pdf.SetFont("Arial", "B", 10)
	pdf.CellFormat(50, 6, label+":", "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	if value == "" {
		value = "N/A"
	}
	pdf.CellFormat(140, 6, value, "", 1, "L", false, 0, "")
}

func strVal(p *string) string {
	if p == nil {
		return "N/A"
	}
	return *p
}

func intVal(p *int) string {
	if p == nil {
		return "N/A"
	}
	return fmt.Sprintf("%d", *p)
}
